### ISSUE TITLE
Export binaries

### ISSUE THREAD

**Issue by escowles** [pulibrary/grocer#5]
Because we are using external content, exporting from Fedora will only get us metadata and URLs pointing at the content files.  One option is to update the export utility to export binaries instead of just pointers for external content (see https://jira.duraspace.org/browse/FCREPO-2382).

**Comment by escowles** [comment]
I have a PR in to add an option to the export utility to retrieve and export external content:  https://github.com/fcrepo4-labs/fcrepo-import-export/pull/74

**Comment by jpstroop** [comment]
:+1:
